### ISSUE TITLE
因子の部屋での大きな数のデコードが正しくされない

### ISSUE THREAD

**Issue by Filexor** [sabo2/pzprjs#1]
http://pzv.jp/p.html?factors/9/9/000000000000000000000000000000$459b0
のような値を設定して出力されたURIを開くと、0x459b0+77776=362880となるはずが78889となってしまう

**Comment by sabo2** [comment]
デコードの際URL中桁数の指定を誤っていました。。
修正とテストを 6f45c494379e で追加しておきました
次のリリース(１週間以内、遅くても今月中)で適用します

**Comment by sabo2** [comment]
v0.10.0にて修正を適用しましたのでissueをcloseします
