### ISSUE TITLE
dead end markings in kouchoku seem broken

### ISSUE THREAD

**Issue by robx** [sabo2/pzprjs#2]
When you draw an unclosed loop in kouchou, errors color the next-to-dead-ends red, not the dead-ends themselves.
<img width="453" alt="screenshot 2019-03-05 at 22 10 33" src="https://user-images.githubusercontent.com/132113/53837883-013d1200-3f94-11e9-9033-0ee4c5fbd2b7.png">

**Comment by sabo2** [comment]
Thank you for your notification. I have fixed this at a38c2bad.
I added the beta tag v0.10.1-beta1, but please wait for a while to be released.
